- Grandpa Spoon/grandpa-spoon.ino
Added code for Grandpa Spoon project for people suffering from hand tremors.
> Added Grandpa Spoon

- Covid Tracker/Covid-Tracker.py
- Grandpa Spoon/grandpa-spoon.ino
Added code for Covid Tracker in Python.
> Add Covid Tracker

- README.md
> init README #18

- 7 Segment Display/7-Segment-Display.cpp
Added the code for 7 Segment Display in C++.
Seven segment displays are the output display device that provide a way to display information in the form of image or text or decimal numbers which is an alternative to the more complex dot matrix displays. It is widely used in digital clocks, basic calculators, electronic meters, and other electronic devices that display numerical information. It consists of seven segments of light emitting diodes (LEDs) which is assembled like numerical 8.
> Add 7 Segment Display

- Meme generator/README.md
- Meme generator/package-lock.json
- Meme generator/package.json
- Meme generator/public/index.html
- Meme generator/src/App.jsx
- Meme generator/src/components/Meme.jsx
- Meme generator/src/components/Templates.jsx
- Meme generator/src/index.js
- Meme generator/src/styles/App.css
- Quiz web app/index.html
- Quiz web app/script.js
- Quiz web app/style.css
> INITIAL COMMIT

- Weather App/README.md
- Weather App/package-lock.json
- Weather App/package.json
- Weather App/public/index.html
- Weather App/src/App.jsx
- Weather App/src/index.js
- Weather App/src/styles/App.css
> Add Weather App

- Grandpa Spoon/README.md
Initialized the repository with README.
> Initialize README.md

- Meme generator/README.md
- grocery_list/README.md
> add README.md to grocery_list 

- Desktop-Weather-App/CONTRIBUTING.md
- Meme generator/CONTRIBUTING.md
Fixes #51
- Change 1
- Change 2
> Add CONTRIBUTING.md

- 2048/app.js
- 2048/index.html
- 2048/style.css
- Algorithms Hub/sortingAlgo/quickSort/quickSort.py
> Added QUICK_SORT ALGO

- Rock Paper Scissors Game/README.md
- To-do webpage/README.md
Fixed Issue #46 
Fixed Issue #48
> Added documentation for Rock Paper Scissors Game

- Algorithms Hub/sortingAlgo/countingSort/countingSort.py
For ex: Fixed Issue #92
- Change 1
- Change 2
> Added counting sort algo using python

- Heath App/README.md
Fixes #40
- Change 1
- Change 2
> Documentation Added

- Algorithms Hub/sortingAlgo/selectionSort/selectionSort.cpp
Fixed Issue #101
- Added selection sort in Algorithms Hub
- None
> Add selection sort

- Scientific-Calculator/README.md
- Scientific-Calculator/index.html
- Scientific-Calculator/script.js
- Scientific-Calculator/style.css
For ex: Fixed Issue #32 
Added Scientific Calculator Project
> Scientific-calculator project added

- Algorithms Hub/sortingAlgo/insertionSort/insertion.c
> Added insertion sort

- BMICalculator/index.html
I made a body mass index calculator
> Body Mass Index Calculator

- Algorithms Hub/searchingAlgo/interpolationSearch/Interpolation Search.cpp
> Added C++ file for Interpolation Search

- Algorithms Hub/sortingAlgo/mergeSort/MergeSort.c
Fixed Issue #96 
- Merge sort added in C
> MergeSort Algo in C added

- Block-Manupulation/script.js
#116 
- Fixed typo error in variable usage
- [*] Tests
- [*] Starred the repo
> fixed typo in code

- Block-Manupulation/README.md
> Updated Readme

- Algorithms Hub/searchingAlgo/kmpSearch/kmp search algorithm.cpp
> Added C++ Algorithm for kmp search

- Algorithms Hub/searchingAlgo/binarySearch/BinarySearch.java
> added binary search in java to algorithms hub

- Dots and Boxes/Dots-and-Boxes.py
- Dots and Boxes/README.md
Added code for Dots and Boxes in Python.
> Add Dots and Boxes

- .vscode/settings.json
- Beginner Javascript Quiz/quiz.html
- Beginner Javascript Quiz/style.css
> Updated css

- ReactWeb/README.md
- ReactWeb/package-lock.json
- ReactWeb/package.json
- ReactWeb/public/index.html
- ReactWeb/src/App.jsx
- ReactWeb/src/context/AuthContext.jsx
- ReactWeb/src/index.js
- ReactWeb/src/router/About.jsx
- ReactWeb/src/router/Dashboard.jsx
- ReactWeb/src/router/Home.jsx
- ReactWeb/src/router/Profile.jsx
- ReactWeb/src/styles/App.css
A simple react JS website using bootstrap
- Added Website
> ADD reactWeb

- Algorithms Hub/sortingAlgo/bubbleSort/bubblesort.js
- Fixed Issue: #89
- The code consists of a bubble sort function which takes an array as input and provides the sorted array as an output.
- Input array: [234, 43, 55, 63, 5, 6, 235, 547]
- Output array: [5,   6,  43,  55, 63, 234, 235, 547]
> Add the code of bubble sort in javascript

- Beginner Javascript Quiz/Script.js
- Beginner Javascript Quiz/index.html
- Beginner Javascript Quiz/results.html
For ex: Fixed Issue #125 
- Replaced `onclick="login()"` attribute with `id="login-button"`
- Added a Password input field next to Email address input
- Added an eventListener for `login-button`'s `click` action
- Changed the `returnToHome()` function for correct redirection to Home.html from quiz.html post quiz
- Post quiz redirection was not functional before hence changed the returnToHome() function
> Fixed login issue in Beginner Javascript Quiz directory

- Algorithms Hub/sortingAlgo/bubbleSort/BubbleSort.c
The code consists of the Bubble sort algorithm which takes input aa array and returns the sorted array.
- Fixed Issue #89 
- The code consists of the Bubble sort algorithm which takes input aa array and returns the sorted array.
> Add the code of Bubble Sort in C

- YourTextSite/src/components/TextForm.css
- YourTextSite/src/components/TextForm.js
Closes Issue #128 
I needed to change the HTML markup in TextForm.js a little bit for proper styling
> Add border and styling to the text output area

- Drum Kit/CONTRIBUTING.md
- Drum Kit/README.md
For ex: Fixed Issue #39 
- Change 1
- Change 2
- [ Done] Documentation
> Documentation Section

- Algorithms Hub/sortingAlgo/ShellSort/shellsort.c
- Algorithms Hub/sortingAlgo/ShellSort/shellsort.cpp
- Algorithms Hub/sortingAlgo/ShellSort/shellsort.java
-  Fixed Issue #88 
- Code takes an array and its size as an input and provides the sorted array in return.
> Add the code for C++, Java and C

- Algorithms Hub/sortingAlgo/countingSort/countingSort.java
- Fixed Issue #92 
- Added countingSort in Java
> countingSort in Java

- Algorithms Hub/searchingAlgo/sublistSearch/SublistSearch.py
For ex: Fixed Issue #86
- Change 1
- Change 2
> added sublist search using python

- Algorithms Hub/sortingAlgo/bubbleSort/bubbleSort.java
- DiceGame/.project
- DiceGame/.settings/org.eclipse.buildship.core.prefs
For ex: Fixed Issue #89
- Change 1
- Change 2
> Added bubble sort algorithm in java

- Algorithms Hub/searchingAlgo/linearSearch/LinearSearchPython.py
- Algorithms Hub/sortingAlgo/insertionSort/InsertionSort.cpp
Fixed Issue #84 
- Linear Search in python added
> LinearSearch Algo in Python added

- Algorithms Hub/sortingAlgo/insertionSort/InsertionSort.java
- Add java files for Insertion Sort
> Added Java File

- Algorithms Hub/searchingAlgo/binarySearch/Binary-Search.cpp
Fixed Issue #72.
Added code for Binary Search algorithm in C++.
> Add Binary Search

- Algorithms Hub/searchingAlgo/binarySearch/binarySearch.java
Fixed Issue #72 
- Binary Search in Java has been added
- None
> Add binary search java code

- DiceGame/readme.txt
> added readme

- TinDog/css/styles.css
Changed the  the carousel section and fixed the button bug.
> fixed issue #147

- Algorithms Hub/sortingAlgo/radixSort/RadixSort.js
I have added RadixSort Algorithm code in JS.
- Fixed Issue #100
> radix sort code added in js

- Algorithms Hub/sortingAlgo/combSort/CombSort.js
> Comb sort code added in js

- Algorithms Hub/searchingAlgo/ternarySearch/TernarySearch.js
> ternary search code added in js

- Algorithms Hub/searchingAlgo/sublistSearch/SublistSearch.js
> Added Sublist search algo code in js

- Algorithms Hub/searchingAlgo/jumpSearch/JumpSearch.js
> Added Jump search algo in js

- Rock Paper Scissors Game/style.css
#195 
- Added some design to the score board of rock-paper-scissor game
- gave some depth effect to the score board.
> Added some design to the score board of rock-paper-scissor game

- Algorithms Hub/searchingAlgo/fibonacciSearch/FibonacciSearch.js
> Fibonacci Search algo code added in js

- Algorithms Hub/searchingAlgo/ternarySearch/ternarySearch.cpp
For ex: Fixed Issue #87
- Change 1
- Change 2
> Added ternary searching using cpp

- Algorithms Hub/sortingAlgo/radixSort/radixSort.py
For ex: Fixed Issue #100
- Change 1
- Change 2
> Added Radix Sort in python

- To-do webpage/index.html
- To-do webpage/script.js
For ex: Fixed Issue #194 
- A new task can now be added by "ENTER" key in the input field.  
> Functionality to add a new task by Enter Key

- To-do webpage/README.md
For ex: Fixed Issue #194 
- Added documentation for functionality concerning the adding of a new task throgh the ENTER key in the input field.
> Add documentation for ENTER functionailty

- 7 Segment Display/7-Segment-Display.java
- Fixed Issue #189
- Added JAVA Code for 7 Segment Display
> Added JAVA Code for 7 Segment Display

- DiceGame/Readme.md
- DiceGame/readme.txt
Added a readme file for the DiceGame project
> Added a Readme file

- Algorithms Hub/ClassicalAlgos/dijkstra's_algo/Dijkstra's_algo.cpp
Fixed Issue #102
Added Dijkstra algo in cpp
> Added Dijkstra algo in cpp (Fixed Issue #102)

- Algorithms Hub/sortingAlgo/cycleSort/Cyclesort.java
- Algorithms Hub/sortingAlgo/cycleSort/Cyclesort.js
- Algorithms Hub/sortingAlgo/cycleSort/Cyclesort.py
- Algorithms Hub/sortingAlgo/heapSort/HeapSort.java
- Algorithms Hub/sortingAlgo/heapSort/HeapSort.js
- Algorithms Hub/sortingAlgo/heapSort/HeapSort.py
- Fixed Issue #94
- Added algorithm of HeapSort in Java, js, and HeapSort.
> Algorithm of HeapSort in Java, js and HeapSort.

- Algorithms Hub/ClassicalAlgos/dijkstra's_algo/dijkstraalgo.py
> added dijkstra algo in python

- README.md
I have added my name under maintainers in README.
> Added my name under maintainers in README

- YourTextSite/src/components/TextForm.css
- YourTextSite/src/components/TextForm.js
#206 
added bold button to  YourTextSite
> Bold button

- Algorithms Hub/searchingAlgo/exponentialSearch/ExponentialSearch.cpp
- Algorithms Hub/searchingAlgo/exponentialSearch/ExponentialSearch.js
I have added code for exponential search algo in c++ and js.
Fixed Issue #73
> Added code for exponential search in c++ and js

- Algorithms Hub/searchingAlgo/fibonacciSearch/Fibonacci-Search.cpp
Fixed Issue #80.
Added code for Fibonacci Search algorithm in C++.
> Add Fibonacci Search

- insect_hit_game/index.html
- insect_hit_game/script.js
- insect_hit_game/style.css
This is minor open source project Insect Hit game .
#32 
#Which all tech stack can it be from?
> Added Insect hit game file

- PasswordChecker/README.md
- PasswordChecker/checkpass.py
- Added Password Checker code. It checks how many times a password has been used on the internet using the HaveIBeenPwned API and lets you know beforehand if your password is strong or not.
- Change 1
- Change 2
> Added Password Checker Project

- Algorithms Hub/searchingAlgo/linearSearch/LinearSearch.java
- Algorithms Hub/searchingAlgo/linearSearch/LinearSearch.js
- Algorithms Hub/searchingAlgo/linearSearch/LinearSearch.php
Fixed Issue #84
-  Added code for LinearSearch in java, javascript, and PHP.
>  Added code for LinearSearch

- Algorithms Hub/searchingAlgo/binarySearch/binarySearch.java
- Algorithms Hub/searchingAlgo/rabinKarpSearch/rabinKarp.java
For ex: Fixed Issue #85 
- rabinKarp Search algo added
- Binary Search changes Done
> Rabin Karp and Binary Search added

- Algorithms Hub/sortingAlgo/pigeonholeSort/Pigeonhole-Sort.py
Fixed Issue #97. 
Added code for Pigeonhole Sort algorithm in Python.
> Add Pigeonhole Sort

- Calculator/index.html
- Calculator/style.css
Fixed Issue #216 
- Made the site responsive
- Done some formatting by removing unnecessary classes and also done some padding .
- Removed unnecessary diagonal nav bar to a horizontal one cause was not looking so good and also changed the height and width of the calculator as the screen was looking so empty.
:
inal screenshots ** | ** updated screenshot **
> Made responsive and did some formatting and also some changes

- Algorithms Hub/sortingAlgo/quickSort/quicksort.java
- Fixed Issue #99
- quicksort code added in java
> quicksort code added in java

- Calculator/style.css
> FIXED #232

- Scientific-Calculator/style.css
> fixes #223  issue ui

- Algorithms Hub/ClassicalAlgos/dijkstra's_algo/Dijkstra's_algo.cpp
> comments added

- Algorithms Hub/sortingAlgo/mergeSort/merge_sort.cpp
> merge sort cpp

- Algorithms Hub/sortingAlgo/radixSort/radix_sort.c
radix sort added in c language
For ex: Fixed Issue #100 
- added the code in C language
> radix_sort.c

- Beginner Javascript Quiz/quiz.html
- Beginner Javascript Quiz/style.css
- Fixed Issue #122
- Changed the layout of the quiz
** original screenshots ** |
** updated screenshot **
> Edited CSS and HTML file of Beginner JS quiz

- Algorithms Hub/searchingAlgo/binarySearch/binarySearch.js
#72 fixed
- Change 1
- Change 2
> Binary Search in JS

- README.md
Updated README.md of MSCxHacktoberfest. Removed the logo and added few animations.
> Update README.md of MSCxHacktoberfest

- Algorithms Hub/searchingAlgo/ternarySearch/ternarySearch.java
> added ternary search code in java

- Health App/Contributors.md.txt
- Health App/Health app.py
> Health App issue resolved

- Music_Player/Contributors.md.txt
- Music_Player/music_player.py
For ex: Fixed Issue #291 
- Change 1
- Change 2
> Music Player Issue Solved

- Beginner Javascript Quiz/Script.js
-Fixed Issue #274 
- Now user has to fill both the login fields in order to move to next page.
> Solved the login issue in index.html

- Algorithms Hub/sortingAlgo/countingSort/countingSort.cs
> added count sort in c#

- Rock Paper Scissors Game/style.css
Fixed Issue #195 by improving UI
- Changed the color scheme of the website to make it more appealing.
- Changed the font of the site.
- Improved the UI due to multiple issues mentioned in the issue section.
|
> improved UI of the page

- Typing Game/index.html
- Typing Game/readme.md.txt
- Typing Game/script.js
- Typing Game/style.css
> Typing Game
